title: Richard Noh | Portfolio
email: richard.jun.noh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  recent grad coder 
github_username: RichardNooooh
minimal_mistakes_skin: dark
domain: richardnooooh.github.io
url: https://richardnooooh.github.io
# search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache

author:
  name   : "Richard Noh"
  avatar : "assets/profile_picture.jpg"
  bio    : "Perpetually tired.. but still chugging on"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RichardNooooh"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rnoh/"
    - label: "Email"
      icon: "fa fa-envelope fa-fw"
      url: "mailto:richard.jun.noh@gmail.com"

footer:
  # links:
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://twitter.com/"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/"
  #   - label: "Instagram"
  #     icon: "fab fa-fw fa-instagram"
  #     url: "https://instagram.com/"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

atom_feed:
  hide: true

after_footer_scripts:
  - /assets/js/projects.js
